### ISSUE TITLE
#managementButton?

### ISSUE THREAD

**Issue by Estigy** [FACT-Finder/FACT-Finder-PHP-Library-Demo#1]
In demo/files/js/demoshop/demoshop.js there are several mentions of img#managementButton. This button appears nowhere else, let alone in the templates.

Is this file necessary at all?

**Comment by tuegeb** [comment]
The demoshop script takes care of the search box and image resizing / error handling. The mentioned button is obsolet.
With 09b6ad7 the demo templates have been cleaned up now.
